apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "initdb.script" . }}
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
data:
{{ (.Files.Glob "scripts/init-db.sh").AsConfig | indent 2 }}