{{/*

Secret file of certificate used for SQL DB encrypted connection

*/}}

{{- if .Values.otdsdb.sslDBRootCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "otdsws.name" . }}-certs
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
data:
  dbRootCA.crt: |-
    {{ .Values.otdsdb.sslDBRootCert | b64enc }}
{{- end }}