{{- if .Values.deploySecretsFromHelm -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels: {{ include "appworks-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if hasKey .Values "database" }}
  AWG_DB_PASSWORD: {{ .Values.database.appworksdb.password | b64enc }}
  {{- else }}
  AWG_DB_PASSWORD: {{ .Values.postgres.appworksdb.password | b64enc }}
  {{- end }}
  {{- if hasKey .Values.awg.settings.mail "smtpPassword" }}
  AWG_OTAG_SMTP_PASSWORD: {{ .Values.awg.settings.mail.smtpPassword }}
  {{- end }}
{{- end }}
