{{- if eq .Values.ingress.enableDCCIngress true }}
## Consul ingress ##
#Ingress Object
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.prefix }}-ingress 
  namespace: {{ .Values.namespace }}  
{{- with .Values.ingress.annotations }}                                       
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if hasKey .Values.ingress "tls" }}
{{- if eq .Values.ingress.tls.enabled true }}
  tls: 
  - hosts: 
    - {{ .Values.ingress.domain }}
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end}}
{{- end}}
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.prefix }}-{{ .Values.consul.prefix }}-service
          servicePort: {{ .Values.consul.service.servicePort }}
        path: /{{ .Values.consul.ingress.uipath }}
      - backend:
          serviceName: {{ .Values.prefix }}-{{ .Values.consul.prefix }}-service
          servicePort: {{ .Values.consul.service.servicePort }}
        path: /{{ .Values.consul.ingress.backendpath }}
{{- if .Values.consul.ingress.host }}
    host: {{ .Values.consul.ingress.host }}
{{ end }}  
{{- if eq .Values.syncagent.enabled true }}      
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.prefix }}-{{ .Values.syncagent.prefix }}-service
          servicePort: {{ .Values.syncagent.service.servicePort }}
        path: /{{ .Values.syncagent.ingress.path }}
  {{- if .Values.syncagent.ingress.host }}
    host: {{ .Values.syncagent.ingress.host }}
  {{ end }}
{{ end }}
{{- if eq .Values.syncnshareManual.enabled true }}
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.prefix }}-{{ .Values.syncnshareManual.prefix }}-service
          servicePort: {{ .Values.syncnshareManual.service.servicePort }}
        path: /{{ .Values.syncnshareManual.ingress.path }}   
 {{- if .Values.syncnshareManual.ingress.host }}
    host: {{ .Values.syncnshareManual.ingress.host }}
 {{ end }}
{{ end }}
{{ end }}