{{ if eq .Values.platform "gcp" }}
{{ if eq .Values.ExtDocbroker.enable true }}
{{ if eq .Values.ExtDocbroker.createExtService true }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName }}        
  name: csext-{{ .Values.serviceName }}
{{ if eq .Values.ExtDocbroker.useLBAnnotations true }}
  annotations:
    {{ toJson .Values.ExtDocbroker.LBAnnotations }}
{{ end }}     
spec:    
  ports:
  - name: csnative
    port: 80
    protocol: TCP
    targetPort: {{ .Values.ports.docbaseport }}
  - name: csssl    
    port: 81
    protocol: TCP
    targetPort: {{ .Values.ports.docbasesslport }}
  selector:
    app: {{ .Values.serviceName }}
  sessionAffinity: ClientIP
  type: LoadBalancer
{{ end }}
{{ end }}
{{ end }}
