apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.resource.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "viewer.name" . }}
    helm.sh/chart: {{ include "viewer.chart" . }}
    app.kubernetes.io/instance: {{ include "base.resource.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "base.resource.name" . }}
      app.kubernetes.io/name: {{ include "viewer.name" . }}
      app.kubernetes.io/instance: {{ include "base.resource.name" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
      labels:
        app: {{ include "base.resource.name" . }}
        app.kubernetes.io/name: {{ include "viewer.name" . }}
        app.kubernetes.io/instance: {{ include "base.resource.name" . }}
        {{- include "otiv.custom.labels" . }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      {{ template "ocp.service.account" . }}
    {{- if and (not .Values.global.usingServiceMesh) (include "is.iv" .) }}
      serviceAccountName: otiv-asecret-sa
      initContainers:
      {{ template "init.otds.container" . }}
    {{- end }}
      containers:
        - name: {{ include "base.resource.name" . }}
          image: {{ include "image.source.path" . }}
          imagePullPolicy: {{ include "image.pull.policy" . }}
          securityContext:
            allowPrivilegeEscalation: false
          ports:
          - name: http
            containerPort: {{ .Values.service.targetPort }}
            protocol: TCP
        {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /viewer/api/v1/health/live
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /viewer/api/v1/health/ready
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /viewer/api/v1/health/ready
              port: http
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
        {{- end }}
          env:
          {{ template "env.resource" . }}
          envFrom:
          - configMapRef:
              name: {{ include "base.resource.name" . }}-configmap
          {{- if .Values.command }}
          command: {{ .Values.command }}
          {{- end }}
    {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
    {{- end }}
