apiVersion: v2
appVersion: "23.2"
dependencies:
- condition: cs-secrets.enabled
  name: cs-secrets
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: kafka-secrets.enabled
  name: kafka-secrets
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: kafka-configMap.enabled
  name: kafka-configMap
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: zookeeper-statefulset.enabled
  name: zookeeper-statefulset
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: kafka-statefulset.enabled
  name: kafka-statefulset
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: db.enabled
  name: db
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "15.2"
- condition: cs-logging-configMap.enabled
  name: cs-logging-configMap
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: docbroker.enabled
  name: docbroker
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: content-server.enabled
  name: content-server
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: dctm-ingress.enabled
  name: dctm-ingress
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: cs-dfc-properties.enabled
  name: cs-dfc-properties
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: dtrbase.enabled
  name: dtrbase
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: 22.4.1
- condition: dctm-rest.enabled
  name: dctm-rest
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: dctm-workflow-designer.enabled
  name: dctm-workflow-designer
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: contentconnect.enabled
  name: contentconnect
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: da.enabled
  name: da
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: dfs.enabled
  name: dfs
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: records.enabled
  name: records
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: rqm.enabled
  name: rqm
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "23.2"
- condition: otds.enabled
  name: otds
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: 23.1.1
- condition: dctm-dcc.enabled
  name: dctm-dcc
  repository: https://artifactory.otxlab.net/artifactory/BPhelm
  version: "22.4"
description: Content server Helm chart for Kubernetes
name: dctm-server
version: "23.2"
