# Default values for metis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

loglevel: 30

replicas: 1

## corresponds to the metis-service
image:
  name: otiv-metis

nameOverride: ""
fullnameOverride: ""

# if true, sets the endpoint to retrieve source files by the metis personas
#   to the metis service's internal k8s url
usePrivateUrl: true

# url of a metis endpoint used to retrieve source files by the metis personas
#   NOTE:if set, this overrides the private url
baseSourceUrl:

resources:
  enabled: false
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 256Mi


service:
  type: ClusterIP
  albType: NodePort
  port: 80
  targetPort: 3000
  # adds listed annotations to all otiv services
  # each entry needs to be a single string that contains a colon ( : ) that separates
  #   the property name and value
  annotations: []

ingress:
  enabled: true

publishingProtocol: https
#publishingHost:
publishingPath: 
#publishingTarget:

# set to false to use full-featured REGULAR license
# for upgrades, does not de-allocate an existing metis license allocation
useBasicLicense: true

publication:
  port: 80

# If set to true, Forwarded/X-Forwarded-Host header whitelist enforcement is enabled
#   and the services validate that the Forwarded/X-Forwarded-* headers adhere to what's 
#   allowed by the forwardedHostsList or forwardedHostsRegex properties.
#
# If set to true and the forwardedHostsList and forwardedHostsRegex are not defined 
#    or have been defined with an invalid syntax, the services will fail to start.
# If both of these properties are configured, forwardedHostsRegex takes precedence.
# The Forwarded/X-Forwarded-Host headers in incoming requests that do not match the
#    properties whitelist criteria are ignroed.
# If not defined here, corresponding global property values are used
#enforceForwardedHosts: false

# a comma seperated list of FQDNs (cannot specify protocols such as https) that are used
#   for validating the Forwarded/X-Forwarded-* headers.
#forwardedHostsList:

# a regex pattern to match FQDNs
# The metacharacter * is a modifier and matches the preceeding character 0 or more times;
#  so * needs to be after another character; typically this will be the metacharacter . (dot)
#  which represents any single character, e.g.: .*site.sample.*
#forwardedHostsRegex:

# if set to true, requests will be only be accepted from the servers listed in corsOriginsList
#  or corsOriginsRegex; if both are defined, corsOriginRegex has precedence
# If not defined here, corresponding global property values are used
#enforceCorsOrigins: false

# a comma seperated list of servers that OTIV services will allow origin requests from
# each origin should start with https:// or http://
#corsOriginsList:

# a regex pattern for servers that OTIV services will allow origin requests from
# The metacharacter * is a modifier and matches the preceeding character 0 or more times;
#  so * needs to be after another character; typically this will be the metacharacter . (dot)
#  which represents any single character. An example value would be: .*site.sample.*
#corsOriginsRegex:
