#---------------------------------------
#Secrets
#---------------------------------------
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secret.name }}
type: Opaque
data:
    broker_admin_username: {{ default "" .Values.kafka_broker.broker_admin_username | b64enc | quote }}
    broker_admin_password: {{ default "" .Values.kafka_broker.broker_admin_password | b64enc | quote }}

