#---------------------------------------
#Service
#---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
spec:
   type: ClusterIP
   ports:
   - port: {{ .Values.kafkabroker.ports.kafkabrkrport }}
     name: kafkabrkrport
   selector:
     app: {{ .Values.serviceName }}
